### PR TITLE
fix(Makefile): Fix target dependency

### PR DESCRIPTION
**Pull request by rtaph**
Fixing a dependency pointing to the wrong script.

### CODE REVIEW

**Comment by rtaph** [comment]
Make some further changes in order to integrate the R data cleaning into the make pipeline. The makefile now implies the following graph:

image

**Comment by d-sel** [comment]
Looks good to me. Only question I have is regarding the data folder structure. 
We have:
`data`
`data\data-processed`
`data-raw`
`data-processed`

Should it not be: 
`data\raw`
`data\processed`
and all files fall within these two folders?

Thanks,
Selma

**Comment by rtaph** [comment]
@d-sel Well we should not have `data/data-processed`, but the others make sense to me. The argument against putting `processed` and `raw` directories in the `data` folder is that an R package will complain about that, because it expects the data directory to contain `.rda` files only.

**Review by d-sel — APPROVED** [review]
I think this is OK to go ahead. In future, we can consider renaming data to data-rda to avoid confusion, but not a big deal at the moment. 

With #23 we should re-direct the google maps output into data-processed instead of data/processed .

**Pull request merged**
